---

version: '3'

services:
  nuxt:
    build: ./
    working_dir: /usr/src/app
    tty: true
    command: npm run dev
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - 3000:3000

volumes:
  node_modules:
    driver: 'local'

