---

version: 2.1

commands:
  build:
    steps:
      - run:
          name: Npm install & build
          command: |
            npm i
            npm run build


jobs:
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run: |
          curl -sL https://deb.nodesource.com/setup_10.x | bash -
          apt-get update
          apt-get install -y nodejs
      - build
      - run: |
          echo $CLIENT_SECRET | base64 --decode > ${HOME}/client-secret.json
          gcloud auth activate-service-account --key-file ${HOME}/client-secret.json
          gsutil rsync -R dist gs://www.tonchim.me
          gsutil acl -r ch -u AllUsers:R gs://www.tonchim.me/

workflows:
  version: 2
  nuxt-cloud-storage:
    jobs:
      - deploy


